use_frameworks!

platform :ios, '9.0'

target 'DLProgressHUD_Example' do
  pod 'DLProgressHUD', :path => '../'

  target 'DLProgressHUD_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
